language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - env: NAME='cargo-travis'
  include:
    - rust: stable
      before_script:
        - rustup component add rustfmt
        - rustup component add clippy
      script:
        - cargo fmt -- --check
        - cargo clippy

before_install:
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      sudo apt-get -qq update
      && sudo apt-get install -y libasound2-dev libudev-dev
      && wget http://libsdl.org/release/SDL2-2.0.5.tar.gz
      && tar -xzvf SDL2-2.0.5.tar.gz
      && pushd SDL2-2.0.5 && ./configure --prefix=/usr && make && sudo make install && popd;
    fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      brew update
      && brew install sdl2;
    fi

script: |
  cargo build --verbose &&
  cargo test  --verbose &&
  cargo doc   --verbose

branches:
  only:
    - staging # bors r+
    - trying  # bors try
    - master

