[package]
name = "prospero"
version = "0.1.0"
authors = ["holmgr <viktor.holmgren@gmail.com>"]
edition = "2018"

[dependencies]
failure = "^0.1"
fern = "^0.5"
chrono = "^0.4"
log = "^0.4"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
